import { test, expect } from '@playwright/test'
import { watch, openWorkbook, clickCell, domCellText, rawOf, cellPoint, apiCall, uid, waitGrid, typeInto, flushSaves, shot } from './helpers.js'

test('SUM and cross-sheet references recalculate immediately', async ({ page }) => {
  const w = watch(page)
  await openWorkbook(page)
  await clickCell(page, 'A1')
  for (const v of ['1', '2', '3', '=SUM(A1:A3)']) {
    await page.keyboard.type(v)
    await page.keyboard.press('Enter')
  }
  expect(await domCellText(page, 'A4')).toBe('6')
  await typeInto(page, 'A2', '12')
  expect(await domCellText(page, 'A4')).toBe('16')

  await page.locator('.sheet-tab-add').click()
  await expect(page.locator('.sheet-tab.is-active')).toHaveText('Sheet2')
  await typeInto(page, 'A1', '5')
  await page.locator('.sheet-tab', { hasText: 'Sheet1' }).click()
  await typeInto(page, 'B1', '=Sheet2!A1*2')
  expect(await domCellText(page, 'B1')).toBe('10')
  await page.locator('.sheet-tab', { hasText: 'Sheet2' }).click()
  await typeInto(page, 'A1', '21')
  await page.locator('.sheet-tab', { hasText: 'Sheet1' }).click()
  expect(await domCellText(page, 'B1')).toBe('42')
  expect(w.errors).toEqual([])
})

test('cross-workbook reference [Title]Sheet1!A1 resolves and survives reload', async ({ page }) => {
  const w = watch(page)
  await openWorkbook(page)
  const title = `Rates ${uid()}`
  const other = (await apiCall(page, 'POST', '/api/modules', { type: 'sheet', title })).body
  const otherData = (await apiCall(page, 'GET', `/api/sheets/${other.id}`)).body
  const sid = otherData.sheets[0].id
  await apiCall(page, 'POST', `/api/sheets/${other.id}/cells`, { cells: [{ sheet: sid, row: 0, col: 0, raw: '8' }, { sheet: sid, row: 1, col: 0, raw: '=A1*5' }] })

  await typeInto(page, 'A1', `=[${title}]Sheet1!A1+1`)
  await expect.poll(() => domCellText(page, 'A1')).toBe('9')
  await typeInto(page, 'A2', `=[${title}]Sheet1!A2`)
  await expect.poll(() => domCellText(page, 'A2')).toBe('40')
  await typeInto(page, 'A3', '=[No such book]Sheet1!A1')
  await expect.poll(() => domCellText(page, 'A3')).toBe('#REF!')
  await flushSaves(page)

  await page.reload()
  await waitGrid(page)
  await expect.poll(() => domCellText(page, 'A1')).toBe('9')
  await expect.poll(() => domCellText(page, 'A2')).toBe('40')
  expect(await rawOf(page, 'A1')).toBe(`=[${title}]Sheet1!A1+1`)
  expect(w.errors).toEqual([])
})

test('errors render distinctly with an explanatory tooltip', async ({ page }) => {
  await openWorkbook(page)
  await typeInto(page, 'A1', '=1/0')
  await typeInto(page, 'A2', '=NOPE(1)')
  await typeInto(page, 'A3', '5')
  expect(await domCellText(page, 'A1')).toBe('#DIV/0!')
  const p = await cellPoint(page, 0, 0)
  const cls = await page.evaluate(({ x, y }) => document.elementsFromPoint(x, y).find((e) => e.classList.contains('sheet-cell')).className, p)
  expect(cls).toContain('is-error')
  const okCls = await page.evaluate(({ x, y }) => document.elementsFromPoint(x, y).find((e) => e.classList.contains('sheet-cell')).className, await cellPoint(page, 2, 0))
  expect(okCls).not.toContain('is-error')
  const colours = await page.evaluate(({ a, b }) => [a, b].map(({ x, y }) => getComputedStyle(document.elementsFromPoint(x, y).find((e) => e.classList.contains('sheet-cell'))).color), { a: p, b: await cellPoint(page, 2, 0) })
  expect(colours[0]).not.toBe(colours[1])

  await page.mouse.move(p.x, p.y)
  const tip = page.locator('.sheet-tooltip')
  await expect(tip).toBeVisible()
  await expect(tip).toContainText('#DIV/0!')
  await expect(tip).toContainText('Division by zero')
  const p2 = await cellPoint(page, 1, 0)
  await page.mouse.move(p2.x, p2.y)
  await expect(tip).toContainText('Unknown name')
  const p3 = await cellPoint(page, 2, 0)
  await page.mouse.move(p3.x, p3.y)
  await expect(tip).toBeHidden()
})

test('pointing works across sheets and returns to the edited cell on commit', async ({ page }) => {
  await openWorkbook(page)
  await page.locator('.sheet-tab-add').click()
  await typeInto(page, 'B2', '9')
  await page.locator('.sheet-tab', { hasText: 'Sheet1' }).click()
  await clickCell(page, 'A1')
  await page.keyboard.type('=')
  await page.locator('.sheet-tab', { hasText: 'Sheet2' }).click()
  await expect(page.locator('.sheet-tab.is-active')).toHaveText('Sheet2')
  await clickCell(page, 'B2')
  await expect(page.locator('.sheet-fx-input')).toHaveValue('=Sheet2!B2')
  await page.keyboard.type('*2')
  await page.keyboard.press('Enter')
  await expect(page.locator('.sheet-tab.is-active')).toHaveText('Sheet1')
  expect(await rawOf(page, 'A1')).toBe('=Sheet2!B2*2')
  expect(await domCellText(page, 'A1')).toBe('18')
})

test('typing =SU shows SUM, SUMIF and SUMIFS with signatures, selectable by keyboard', async ({ page }) => {
  await openWorkbook(page)
  await clickCell(page, 'B2')
  await page.keyboard.type('=SU')
  const ac = page.locator('.sheet-ac')
  await expect(ac).toBeVisible()
  const names = await ac.locator('.sheet-ac-name').allTextContents()
  for (const n of ['SUM', 'SUMIF', 'SUMIFS']) expect(names).toContain(n)
  const sumifRow = ac.locator('.sheet-ac-item', { has: page.locator('.sheet-ac-name', { hasText: /^SUMIF$/ }) })
  await expect(sumifRow.locator('.sheet-ac-sig')).toContainText('SUMIF(')
  while (await ac.locator('.is-selected .sheet-ac-name').textContent() !== 'SUMIF') await page.keyboard.press('ArrowDown')
  await expect(ac.locator('.sheet-ac-detail')).toContainText('SUMIF(')
  await page.keyboard.press('Enter')
  await expect(ac).toBeHidden()
  await expect(page.locator('.sheet-editor')).toHaveValue('=SUMIF(')
  await page.keyboard.press('Escape')
  expect(await rawOf(page, 'B2')).toBe('')
})

test('pointing inserts references while typing a formula, with coloured highlights', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await openWorkbook(page)
  await typeInto(page, 'B2', '3')
  await typeInto(page, 'C1', '4')
  await typeInto(page, 'C2', '5')
  await typeInto(page, 'C3', '6')
  await clickCell(page, 'E2')
  await page.keyboard.type('=')
  await clickCell(page, 'B2')
  await expect(page.locator('.sheet-editor')).toHaveValue('=B2')
  await page.keyboard.type('+SUM(')
  const a = await cellPoint(page, 0, 2)
  const b = await cellPoint(page, 2, 2)
  await page.mouse.move(a.x, a.y)
  await page.mouse.down()
  await page.mouse.move(b.x, b.y, { steps: 5 })
  await page.mouse.up()
  await expect(page.locator('.sheet-editor')).toHaveValue('=B2+SUM(C1:C3')
  const refs = page.locator('.pane-main .ov-ref')
  await expect(refs).toHaveCount(2)
  const colours = await refs.evaluateAll((els) => els.map((e) => getComputedStyle(e).borderTopColor))
  expect(colours[0]).not.toBe(colours[1])
  // Keyboard pointing: after an operator, arrows move a reference instead of leaving the cell
  await page.keyboard.type(')*')
  await page.keyboard.press('ArrowLeft')
  await expect(page.locator('.sheet-editor')).toHaveValue('=B2+SUM(C1:C3)*D2')
  await shot(page, 'formula-pointing')
  await page.keyboard.press('Enter')
  expect(await rawOf(page, 'E2')).toBe('=B2+SUM(C1:C3)*D2')
  expect(await domCellText(page, 'E2')).toBe('3')
  await typeInto(page, 'D2', '2')
  expect(await domCellText(page, 'E2')).toBe('33')
})
